name: CI Checks
on:
  push:
    branches:
      -main
jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:


    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.23

    - name: Checkout code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make build
    
    - name: Copy files
      run: | 
            mkdir artifacts
            cp web artifacts/.

    - name: Archive
      uses: actions/upload-artifacts@v2
      with:
        name: api
        path: artifacts